name: nylon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.2.2
  font_awesome_flutter: ^10.7.0


  get: ^4.6.6
  http: ^1.2.1
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  otp_text_field: ^1.1.3
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  intl: ^0.20.1
  intl_phone_field: ^3.2.0
  awesome_dialog: ^3.0.2
  carousel_slider: ^5.0.0
  easy_stepper: ^0.8.3
  flutter_fortune_wheel: ^1.3.0
  rxdart: ^0.28.0
  animate_do: ^3.3.4
  percent_indicator: ^4.2.3
  cached_network_image: ^3.4.1
  dropdown_search: ^6.0.1
  drop_down_search_field: ^1.0.6
  image_picker: ^1.1.2
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.14.3"

flutter_icons:
  android: true
  ios: true
  image_path: "images/logoNylon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/logoNylon.png
    - images/riyalsymbol_compressed.png
    - images/bank_transfer.png
    - images/xpayment1.png
    - images/tabby_installments.png
    - images/cod.png
    - images/tamara-logo-badge-ar.svg

  fonts:
    - family: ar
      fonts:
        - asset: fonts/ar/new/Tajawal-Bold.ttf
          weight: 900
        - asset: fonts/ar/new/Tajawal-Medium.ttf
          weight: 700
        - asset: fonts/ar/new/Tajawal-Medium.ttf
          weight: 500
        - asset: fonts/ar/new/Tajawal-Regular.ttf
          weight: 400
    - family: en
      fonts:
        - asset: fonts/en/Lato-Black.ttf
          weight: 900
        - asset: fonts/en/Lato-Bold.ttf
          weight: 700
        - asset: fonts/en/Lato-Light.ttf
          weight: 300
        - asset: fonts/en/Lato-Regular.ttf
          weight: 400
