// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKvfsDJ9vvAL02qiViln1-g2NnAduLEMM',
    appId: '1:1088051047885:android:640ced6fda04665da2a884',
    messagingSenderId: '1088051047885',
    projectId: 'nylonsa-finial-project8-27',
    storageBucket: 'nylonsa-finial-project8-27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyAKvfsDJ9vvAL02qiViln1-g2NnAduLEMM', // هتحتاج تضيف iOS app في Firebase Console
    appId:
        '1:1088051047885:ios:ios:7e613dc25d15d758a2a884', // هتحتاج تضيف iOS app في Firebase Console
    messagingSenderId: '1088051047885',
    projectId: 'nylonsa-finial-project8-27',
    storageBucket: 'nylonsa-finial-project8-27.firebasestorage.app',
    iosBundleId: 'com.nylonsa.app',
  );
}
